### PR TITLE
Changes to Migrate to listAdapter

### PR DESCRIPTION
**Pull request by kanake10**
Small PR to add the following functionality:

- Migrate to listadapter
- use glide to load image
- running CI using github actions

### CODE REVIEW

**Comment by hamzaazman** [comment]
Thanks for contributing. :)

**Comment by kanake10** [comment]
> 

Nice application 🥳🥳.
Learnt some technologies from it.

**Comment by hamzaazman** [comment]
I have to problem with the actions. I've never used github actions and researching this now. :)

**Comment by kanake10** [comment]
> I have to problem with the actions. I've never used github actions and researching this now. :)

Sharing resources to help you through:

1. https://www.geeksforgeeks.org/basic-ci-workflow-for-android-using-github-actions/?ref=rp
2. https://www.geeksforgeeks.org/github-actions-for-android/
3. https://www.youtube.com/watch?v=K9w01h4-Wnc&t=548s
4. https://www.youtube.com/watch?v=SVLyADb8rQc&t=2s

In case you are stuck, let me know

**Comment by hamzaazman** [comment]
Thanks for sharing resources. You're in my mind.

**Pull request merged**
